#pragma once

#define TP_RET_CODE_SUCCESS						0
#define TP_RET_CODE_NO_CHANGES_SUCCESS			1
#define TP_RET_CODE_EXPORT_OK					2
#define TP_RET_CODE_SHARE_OK					3
#define TP_RET_CODE_IMPORT_OK					4
#define TP_RET_CODE_CUSTOM_SUCCESS				10

#define TP_RET_CODE_CUSTOM_ERROR				100
#define TP_RET_CODE_UNKNOWN_ERROR				101
#define TP_RET_CODE_FILE_NOT_FOUND				102
#define TP_RET_CODE_DIRECTORY_NOT_FOUND			103
#define TP_RET_CODE_FILE_NOT_WRITABLE			104
#define TP_RET_CODE_DIRECTORY_NOT_WRITABLE		105
#define TP_RET_CODE_UNKOWN_FILE_TYPE			106
#define TP_RET_CODE_CORRUPT_FILE				107
#define TP_RET_CODE_OPEN_CREATE_FAILED			108
#define TP_RET_CODE_OPEN_READ_FAILED			109
#define TP_RET_CODE_OPEN_WRITE_FAILED			110
#define TP_RET_CODE_CREATE_DIR_FAILED			111
#define TP_RET_CODE_READ_FAILED					112
#define TP_RET_CODE_WRITE_FAILED				113
#define TP_RET_CODE_EXEC_FAILED					114
#define TP_RET_CODE_DIRECTORY_EMPTY				115
#define TP_RET_CODE_CONNECTION_ABORTED			116
#define TP_RET_CODE_UPLOAD_FAILED				117
#define TP_RET_CODE_DOWNLOAD_FAILED				118
#define TP_RET_CODE_INVALID_REQUEST_METHOD		119
#define TP_RET_CODE_WRONG_PASSWORD				120
#define TP_RET_CODE_USER_DOES_NOT_EXIST			121
#define TP_RET_CODE_SERVER_PAUSED				122
#define TP_RET_CODE_NO_DEVICE_ID				123
#define TP_RET_CODE_DEVICEID_NOT_REGISTERED		124
#define TP_RET_CODE_ARGUMENT_MISSING			125
#define TP_RET_CODE_PASSWORD_MISSING			126
#define TP_RET_CODE_SERVER_UNREACHABLE			127
#define TP_RET_CODE_CANNOT_ACCESS_INTERNET		128
#define TP_RET_CODE_FILE_MOVE_FAILED			129
#define TP_RET_CODE_AUTHENTICATION_FAILED		130
#define TP_RET_CODE_UPDATE_FAILED				131
#define TP_RET_CODE_INSERT_FAILED				132
#define TP_RET_CODE_DELETE_FAILED				133
#define TP_RET_CODE_IMPORT_FAILED				134
#define TP_RET_CODE_EXPORT_FAILED				135
#define TP_RET_CODE_WRONG_IMPORT_FILE_TYPE		136
#define TP_RET_CODE_SHARE_FAILED				137

#define TP_RET_CODE_CUSTOM_WARNING				300
#define TP_RET_CODE_NOTHING_TODO				301
#define TP_RET_CODE_OPERATION_CANCELED			302
#define TP_RET_CODE_NO_MESO						303
#define TP_RET_CODE_NOTHING_TO_EXPORT			304

#define TP_RET_CODE_CUSTOM_MESSAGE				500

#define TP_RET_CODE_DEFERRED_ACTION				800

