#pragma once

#define TP_RET_CODE_SUCCESS 0
#define TP_RET_CODE_FILE_NOT_FOUND 1
#define TP_RET_CODE_DIRECTORY_NOT_FOUND 2
#define TP_RET_CODE_FILE_NOT_WRITABLE 3
#define TP_RET_CODE_DIRECTORY_NOT_WRITABLE 4
#define TP_RET_CODE_UNKOWN_FILE_TYPE 5
#define TP_RET_CODE_CORRUPT_FILE 6
#define TP_RET_CODE_OPEN_CREATE_FAILED 7
#define TP_RET_CODE_OPEN_READ_FAILED 8
#define TP_RET_CODE_OPEN_WRITE_FAILED 9
#define TP_RET_CODE_CREATE_DIR_FAILED 10
#define TP_RET_CODE_READ_FAILED 11
#define TP_RET_CODE_WRITE_FAILED 12
#define TP_RET_CODE_DIRECTORY_EMPTY 13
#define TP_RET_CODE_CONNECTION_ABORTED 14
#define TP_RET_CODE_UPLOAD_FAILED 15
#define TP_RET_CODE_DOWNLOAD_FAILED 16
#define TP_RET_CODE_INVALID_REQUEST_METHOD 17
#define TP_RET_CODE_WRONG_PASSWORD 18
#define TP_RET_CODE_USER_DOES_NOT_EXIST 19
#define TP_RET_CODE_SERVER_PAUSED 20
#define TP_RET_CODE_NO_DEVICE_ID 21
#define TP_RET_CODE_DEVICEID_NOT_REGISTERED 22
#define TP_RET_CODE_ARGUMENT_MISSING 23
#define TP_RET_CODE_PASSWORD_MISSING 24
#define TP_RET_CODE_SERVER_DOWN 25
#define TP_RET_CODE_CANNOT_ACCESS_INTERNET 26
#define TP_RET_CODE_FILE_MOVE_FAILED 27
#define TP_RET_CODE_AUTHENTICATION_FAILED 28
#define TP_RET_CODE_NO_CHANGES_SUCCESS 29
#define TP_RET_CODE_UPDATE_FAILED 30
#define TP_RET_CODE_INSERT_FAILED 31
#define TP_RET_CODE_DELETE_FAILED 32
#define TP_RET_CODE_IMPORT_FAILED 33
#define TP_RET_CODE_EXPORT_FAILED 34
#define TP_RET_CODE_NOTHING_TODO 35
#define TP_RET_CODE_OPERATION_CANCELED 36

#define TP_RET_CODE_UNKNOWN_ERROR 100

#define TP_RET_CODE_CUSTOM_SUCCESSES 300
#define TP_RET_CODE_EXPORT_OK 301
#define TP_RET_CODE_SHARE_OK 302
#define TP_RET_CODE_IMPORT_OK 303

#define TP_RET_CODE_CUSTOM_ERRORS 400
#define TP_RET_CODE_WRONG_IMPORT_FILE_TYPE 401
#define TP_RET_CODE_SHARE_FAILED 402
#define TP_RET_CODE_NO_MESO 403
#define TP_RET_CODE_NOTHING_TO_EXPORT 404

#define TP_RET_CODE_CUSTOM_MESSAGES 500
#define TP_RET_CODE_CUSTOM_WARNINGS 700

#define TP_RET_CODE_DEFERRED_ACTION 2000

